FROM golang:1.8-alpine

MAINTAINER Tit Petric <black@scene-si.org>

RUN apk --update add bash make docker nodejs rsync && go get -u github.com/aktau/github-release && go get -u github.com/jteeuwen/go-bindata/...

WORKDIR /go/src/app
